services:
  nango1:
    user: 1000:1000
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
        USERNAME: okubo
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080" # yarn devした時のport
      - "5000:5000" # firebase serveした時のport
      - "9005:9005" # OAuthに必要なport
      - "3000:3000" # yarn devした時のport
    volumes:
      - .:/myapp
    container_name: nango1